### ISSUE TITLE
how can i use EasyClangComplete and ColorCoder together

### ISSUE THREAD

**Issue by eyun221** [niosus/EasyClangComplete#302]
ColorCoder for sublime can generate pretty beautiful color for C/C++
but EasyClangComplete can not work when ColorCoder installed and enabled syntax from
View --> Syntax --> ColorCoder-->C++ (Colorcode)

Can you fix this，or give  some alternative method to make them work together?

![colorcoder](https://user-images.githubusercontent.com/9376835/29064312-2321a744-7c5b-11e7-9a36-890996da2816.png)

**Comment by niosus** [comment]
It should be easy to fix. Can you show the bottom of the screen to me? What is being shown there? What is the name of the syntax that is being used?

**Comment by eyun221** [comment]
ok, seems sublimeClang on windows can work with colorcoder together .

here is the pic
![colorcoder1](https://user-images.githubusercontent.com/9376835/29104360-8420a224-7cf7-11e7-807b-58e5bcda0914.png)

**Comment by eyun221** [comment]
when enable colorcode syntax，console print following msg：
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "/Users/eyun/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 215, in on_selection_modified
    settings = self.settings_manager.settings_for_view(view)
AttributeError: 'NoneType' object has no attribute 'settings_for_view'
[ECC:ERROR  ]: no view to populate common flags from

**Comment by niosus** [comment]
I have pushed a new release that solves your problem. It will work with version 4.1.2.

**Comment by eyun221** [comment]
thx for fast response
